//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Novelbin.Core.Tests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HtmlFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HtmlFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Novelbin.Core.Tests.Resources.HtmlFiles", typeof(HtmlFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;title&gt;Search: The cursed Prince - Read Novel Online 2024 - Novel Bin&lt;/title&gt;
        ///&lt;meta property=&quot;og:title&quot; content=&quot;Search: The cursed Prince - Read Novel Online 2024 - Novel Bin&quot;&gt;
        ///&lt;meta itemprop=&quot;name&quot; content=&quot;Search: The cursed Prince - Read Novel Online 2024 - Novel Bin&quot;&gt;
        ///&lt;meta name=&quot;description&quot; itemprop=&quot;description&quot; content=&quot;Read best Search: The novels online free, Read daily updated Search: The cursed Prince - Novel Bin&quot;&gt;
        ///&lt;meta property=&quot;og:description&quot; content=&quot;Re [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SearchTheCursedPrinceHtml {
            get {
                return ResourceManager.GetString("SearchTheCursedPrinceHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;title&gt;The Cursed Prince Novel - Read The Cursed Prince Online For Free - Novel Bin&lt;/title&gt;
        ///    &lt;meta property=&quot;og:title&quot; content=&quot;The Cursed Prince Novel - Read The Cursed Prince Online For Free - Novel Bin&quot;&gt;
        ///    &lt;meta itemprop=&quot;name&quot; content=&quot;The Cursed Prince Novel - Read The Cursed Prince Online For Free - Novel Bin&quot;&gt;
        ///    &lt;meta name=&quot;description&quot; itemprop=&quot;description&quot; content=&quot;This book is about baby-making.The crown prince was cursed on the day he was born, th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TheCursedPrinceHtml {
            get {
                return ResourceManager.GetString("TheCursedPrinceHtml", resourceCulture);
            }
        }
    }
}
